import pygame

modifiers = {
    pygame.K_LALT: "",
    pygame.K_RALT: "",
    pygame.K_LSHIFT: "",
    pygame.K_RSHIFT: "",
    pygame.K_LCTRL: "",
    pygame.K_RCTRL: "",
    pygame.K_KP_ENTER: ""
}

lowercase = {
    pygame.K_q: "q",
    pygame.K_w: "w",
    pygame.K_e: "e",
    pygame.K_r: "r",
    pygame.K_t: "t",
    pygame.K_y: "y",
    pygame.K_u: "u",
    pygame.K_i: "i",
    pygame.K_o: "o",
    pygame.K_p: "p",
    pygame.K_a: "a",
    pygame.K_s: "s",
    pygame.K_d: "d",
    pygame.K_f: "f",
    pygame.K_g: "g",
    pygame.K_h: "h",
    pygame.K_j: "j",
    pygame.K_k: "k",
    pygame.K_l: "l",
    pygame.K_z: "z",
    pygame.K_x: "x",
    pygame.K_c: "c",
    pygame.K_v: "v",
    pygame.K_b: "b",
    pygame.K_n: "n",
    pygame.K_m: "m",
    # pygame.K_SPACE: " ",
    pygame.K_0: "0",
    pygame.K_1: "1",
    pygame.K_2: "2",
    pygame.K_3: "3",
    pygame.K_4: "4",
    pygame.K_5: "5",
    pygame.K_6: "6",
    pygame.K_7: "7",
    pygame.K_8: "8",
    pygame.K_9: "9",
    pygame.K_BACKQUOTE: "`",
    pygame.K_MINUS: "-",
    pygame.K_EQUALS: "=",
    pygame.K_LEFTBRACKET: "[",
    pygame.K_RIGHTBRACKET: "]",
    pygame.K_SEMICOLON: ";",
    pygame.K_QUOTE: "'",
    pygame.K_HASH: "#",
    pygame.K_BACKSLASH: "\\", # backslash is not recognised by pygame (somewhat understandably)
    pygame.K_COMMA: ",",      # so if a user wants to use it, then tough luck, they're not getting it
    pygame.K_PERIOD: ".", 
    pygame.K_SLASH: "/",
    pygame.K_KP0: "0", # num pad numbers (key pad)
    pygame.K_KP1: "1",
    pygame.K_KP2: "2",
    pygame.K_KP3: "3",
    pygame.K_KP4: "4",
    pygame.K_KP5: "5",
    pygame.K_KP6: "6",
    pygame.K_KP7: "7",
    pygame.K_KP8: "8",
    pygame.K_KP9: "9",
    pygame.K_KP_DIVIDE: "/",
    pygame.K_KP_EQUALS: "=",
    pygame.K_KP_MINUS: "-",
    pygame.K_KP_MULTIPLY: "*",
    pygame.K_KP_PERIOD: ".",
    pygame.K_KP_PLUS: "+",
    pygame.K_UNKNOWN: "",
    pygame.K_RETURN: "RETURN",
    pygame.K_BACKSPACE: "BSPCE"
}

uppercase = {
    pygame.K_q: "Q",
    pygame.K_w: "W",
    pygame.K_e: "E",
    pygame.K_r: "R",
    pygame.K_t: "T",
    pygame.K_y: "Y",
    pygame.K_u: "U",
    pygame.K_i: "I",
    pygame.K_o: "O",
    pygame.K_p: "P",
    pygame.K_a: "A",
    pygame.K_s: "S",
    pygame.K_d: "D",
    pygame.K_f: "F",
    pygame.K_g: "G",
    pygame.K_h: "H",
    pygame.K_j: "J",
    pygame.K_k: "K",
    pygame.K_l: "L",
    pygame.K_z: "Z",
    pygame.K_x: "X",
    pygame.K_c: "C",
    pygame.K_v: "V",
    pygame.K_b: "B",
    pygame.K_n: "N",
    pygame.K_m: "M",
    pygame.K_SPACE: " ",
    pygame.K_1: "!",
    pygame.K_2: "\"",
    pygame.K_3: "£",
    pygame.K_4: "$",
    pygame.K_5: "%",
    pygame.K_6: "^",
    pygame.K_7: "&",
    pygame.K_8: "*",
    pygame.K_9: "(",
    pygame.K_0: ")",
    pygame.K_BACKQUOTE: "¬", # pygame doesn't seem to detect characters accessed via shift
    pygame.K_MINUS: "_",     # so having a shift boolean plus using regular pygame characters
    pygame.K_EQUALS: "+",    # enables shift-characters to be accessed
    pygame.K_LEFTBRACKET: "{",
    pygame.K_RIGHTBRACKET: "}",
    pygame.K_SEMICOLON: ":",
    pygame.K_QUOTE: "@",
    pygame.K_HASH: "~",
    pygame.K_BACKSLASH: "|", # the backslash issue also occurs here
    pygame.K_COMMA: "<",
    pygame.K_PERIOD: ">", 
    pygame.K_SLASH: "?",

    pygame.K_KP0: "0",
    pygame.K_KP1: "1",
    pygame.K_KP2: "2",
    pygame.K_KP3: "3",
    pygame.K_KP4: "4",
    pygame.K_KP5: "5",
    pygame.K_KP6: "6",
    pygame.K_KP7: "7",
    pygame.K_KP8: "8",
    pygame.K_KP9: "9",
    pygame.K_KP_DIVIDE: "/",
    pygame.K_KP_EQUALS: "=",
    pygame.K_KP_MINUS: "-",
    pygame.K_KP_MULTIPLY: "*",
    pygame.K_KP_PERIOD: ".",
    pygame.K_KP_PLUS: "+",
    pygame.K_UNKNOWN: "",
    pygame.K_RETURN: "RETURN",
    pygame.K_BACKSPACE: "BSPCE"
}


# allkeys = {**lowercase, **uppercase, **modifiers}

# print(allkeys)


    # pygame.K_TAB: "",
    # pygame.K_CURRENCYSUBUNIT: "",
    # pygame.K_CURRENCYUNIT: "",
    # pygame.K_LGUI: "",
    # pygame.K_LMETA: "",
    # pygame.K_LSUPER: "",
    # pygame.K_MENU: "",
    # pygame.K_MODE: "",
    # pygame.K_POWER: "",
    # pygame.K_PRINT: "",
    # pygame.K_RGUI: "",
    # pygame.K_RMETA: "",
    # pygame.K_RSUPER: "",
    # pygame.K_SCROLLLOCK: "",
    # pygame.K_SCROLLOCK: "",
    # pygame.K_SYSREQ: "",
